
format="""
🟡 \
$username\
$directory\
$git_branch\
$git_status\
$git_state\
$time\
\n\
$status\
$character\n"""

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 5
add_newline = false
# Disable the newline at the start of the prompt


[time]
disabled = false
format = '🕙 [\[$time\]]($style) '

[git_status]
conflicted = "conflict|"
untracked = "untracked|"
stashed = "stashed|"
modified = "modified|"
staged = '[++\($count\)](green)'
renamed = "renamed|"
deleted = "deleted|"
ahead = "ahead-${count}|"
diverged = "diverged-${ahead_count}${behind_count}|"
behind = "behding-${count}"
